# Generated by Django 4.1.1 on 2022-09-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('student_id', models.IntegerField()),
                ('dept', models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE')], default='CSE', max_length=5)),
            ],
        ),
    ]
