# Generated by Django 4.1.1 on 2022-09-09 11:00

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_alter_student_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.DecimalField(decimal_places=2, max_digits=3)),
                ('room_no', models.DecimalField(decimal_places=2, help_text='Enter room number.', max_digits=3)),
                ('seat_no', models.DecimalField(decimal_places=2, help_text='Enter seat number.', max_digits=3)),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='query.department')),
            ],
            managers=[
                ('all_employees', django.db.models.manager.Manager()),
            ],
        ),
    ]
