# Generated by Django 4.1.1 on 2022-09-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_department_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='employee',
            name='room_no',
            field=models.DecimalField(decimal_places=2, help_text='Enter room number.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='seat_no',
            field=models.FloatField(help_text='Enter seat number.'),
        ),
    ]
