# Generated by Django 4.1.1 on 2022-09-11 06:07

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('cse_students', django.db.models.manager.Manager()),
            ],
        ),
    ]
