# Generated by Django 4.1.2 on 2023-02-18 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forword_reverse_rlt', '0004_alter_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='forword_reverse_rlt.school'),
        ),
    ]
